name: "Serverless app deployment by Terraform"

on: workflow_dispatch


defaults:
  run:
      working-directory: "terraform"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout
    #   uses: actions/checkout@v2

    # - name: configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-northeast-1

    # - name: Get terraform version
    #   id: tfver
    #   run: echo "::set-output name=tfver::`cat $GITHUB_WORKSPACE/.terraform-version`"

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1
    #   with:
    #     terraform_version: ${{ steps.tfver.outputs.tfver }}

    # - name: Terraform Init
    #   id: init
    #   run: terraform init

    # - name: Terraform Validate
    #   id: validate
    #   run: terraform validate

    # - name: Terraform Plan
    #   id: plan
    #   run: terraform plan -no-color

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve

    - name: Lambda Deploy
      run: ls

